# Generated by Django 4.1.1 on 2022-12-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_test_remove_user_test2_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_data',
            field=models.CharField(default='hello', max_length=256),
        ),
    ]
