# Generated by Django 4.1.1 on 2022-12-04 00:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_company_name_user_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('X', ' ')], default='X', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=150, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, unique=True),
        ),
    ]
