# Generated by Django 4.1.1 on 2022-12-04 00:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_birthdate_user_company_address_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
