# Generated by Django 4.1.1 on 2022-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('code_number', models.IntegerField(blank=True)),
            ],
        ),
    ]
