# Generated by Django 4.1.1 on 2022-09-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_productdataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDataSet',
        ),
    ]
